### ISSUE TITLE
Newest commit breaks scoreboard

### ISSUE THREAD

**Issue by mew1033** [Matir/pwnableweb-scoreboard#101]
The commit from May 24th, e08df0638f60264e1150c2eb34e65652ac81df4b, breaks the createdb function. The part that breaks it is likely in e79ca0a7241ce5205b46eb79f57e33afe2d04aca. Rolling back fixes things.
Steps to reproduce:
1. Launch Amazon Linux AMI
2. Install git and python-pip
3. git clone the repo
4. cd to directory and execute python main.py createdb
5. Get following error:

    Traceback (most recent call last):
      File "main.py", line 17, in <module>
        from scoreboard.app import app
      File "/home/ec2-user/pwnableweb-scoreboard/scoreboard/__init__.py", line 1, in <module>
        from . import app as app_module
      File "/home/ec2-user/pwnableweb-scoreboard/scoreboard/app.py", line 79, in <module>
        app = create_app()
      File "/home/ec2-user/pwnableweb-scoreboard/scoreboard/app.py", line 42, in create_app
        log_formatter = logger.Formatter(
    UnboundLocalError: local variable 'logger' referenced before assignment

6. git checkout b79c2567bdad69022f00536ebdd66adfcb5e6d48
7. Execute python main.py createdb. It works.

**Comment by Matir** [comment]
Hey, please check out the repository at https://github.com/google/ctfscoreboard.  Since we used this for the Google CTF and other Googlers are now working on the project, development has moved there.  (I should fix this repository, sorry for that.)
