### ISSUE TITLE
Make challenges worth progressively less as more people solve them

### ISSUE THREAD

**Issue by mew1033** [Matir/pwnableweb-scoreboard#72]
In a few recent CTFs I've done, the scoring has been a little different. Every challenge is worth a bucket of points, but that bucket is always evenly distributed over all the people who have solved the challenge. That way people are rewarded for solving stuff no one else has been able to solve.

Is there any way you could modify the scoreboard to allow this type of scoring? Maybe with a config option in config.py?

**Comment by Matir** [comment]
Interestingly, one of my coworkers and I have been discussing this very scoring system.  It's definitely possible to do this, and I think it would be a great addition.  I'll look at adding that this weekend.

**Comment by mew1033** [comment]
@Matir Awesome! I'm actually running a CTF this weekend (saturday) and I'm planning on using your scoreboard. I was going to hack at it tonight and see if I could figure out how to modify the scoring method. It's fun to see people's reactions when their score goes _down_. :-)
Modifying it doesn't look incredibly difficult, although I'm not sure I've got the python web app skills to do it successfully.
If you have any directions to point me in, that'd be great.

Thanks!

**Comment by Matir** [comment]
So the way scoring works currently is that when an answer gets submitted, the # of points is recorded is the 'Answer' model, and the team's points get recalculated as well.  (They're stored in a denormalized format because I didn't want to sum(points) every time the teams table is queried.)

To change to this scoring model, I'll probably do a 2-pass approach (which is unfortunately O(n^2), but O(n^2) on answer is preferable to O(n) on every query of the team's score) by inserting the new Answer, finding all other answers for the same question, updating their point value, and then updating those team's scores.

The bigger questions are how to display the point value for the challenge itself: the total point pool, or the current point value based on the # of teams that have solved?

Can I ask what CTF you're running with this?  (Just curious, if it's public anywhere.)

**Comment by mew1033** [comment]
I think it would be best to show the number of points the challenge is currently worth. For example, if the challenge starts out being worth 100 points, and 4 people have solved it, it should show on the gameboard as being a 25 point challenge.

You've already got the attributes there for the challenges: Total points and number of solves. Maybe in addition to recalculating team points on correct answer, you can also recalculate that challenge. Add 1 to the number of solves and divide original points by number of solves. Then maybe add another attribute to show current value or something.

It's a CTF for the security club at my university. I'm a grad student and one of my "classes" was to run a CTF. I've been building challenges all semester and the game is this Saturday.

**Comment by mew1033** [comment]
Not sure if this is the right direction, but here's a start:

```diff --git a/scoreboard/models.py b/scoreboard/models.py
index 28c5f4b..0059c48 100644
--- a/scoreboard/models.py
+++ b/scoreboard/models.py
@@ -297,6 +297,7 @@ class Challenge(db.Model):
     name = db.Column(db.String(100), nullable=False)
     description = db.Column(db.Text, nullable=False)
     points = db.Column(db.Integer, nullable=False)
+    cur_points = db.Column(db.Integer, nullable=False)
     answer_hash = db.Column(db.String(48))  # Protect answers
     unlocked = db.Column(db.Boolean, default=False)
     weight = db.Column(db.Integer, nullable=False)  # Order for display
@@ -330,6 +331,9 @@ class Challenge(db.Model):
     def change_answer(self, answer):
         self.answer_hash = pbkdf2.crypt(answer)

+    def change_cur_points(self, cur_points):
+        self.cur_points = cur_points
+
     @property
     def solves(self):
         return len(self.answers)
@@ -387,6 +391,7 @@ class Challenge(db.Model):
         challenge.name = name
         challenge.description = description
         challenge.points = points
+        challenge.cur_points = points
         challenge.answer_hash = pbkdf2.crypt(answer)
         challenge.cat_cid = cid
         challenge.unlocked = unlocked
```

```diff --git a/scoreboard/controllers.py b/scoreboard/controllers.py
index e3a952d..5bb86b7 100644
--- a/scoreboard/controllers.py
+++ b/scoreboard/controllers.py
@@ -97,9 +97,15 @@ def submit_answer(cid, answer):
                 models.UnlockedHint.team == flask.g.team).all()
             deduction = sum(
                 h.hint.cost for h in hints if h.hint.challenge_cid == cid)
-            points = challenge.points - deduction
-            flask.g.team.score += points
+            # points = challenge.points - deduction
             models.Answer.create(challenge, flask.g.team, answer)
+            points = challenge.cur_points
+            solves = challenge.solves
+            max_points = challenge.points
+            new_points = max_points / solves
+            challenge.change_cur_points(new_points)
+            models.commit()
+            flask.g.team.score += new_points
             models.ScoreHistory.add_entry(flask.g.team)
             correct = 'CORRECT'
             return points
```

**Comment by mew1033** [comment]
Would it work to create a function that recalculates all scores for all teams/users based on the answers and challenges tables? Then you can just add the answer and call the recalculate_points function.

I'm still getting used to the whole sqlalchemy thing...

**Comment by Matir** [comment]
I took a slightly different approach (recalculating current points on the fly rather than storing it) and added the necessary front-end changes.  I did some quick testing locally, but nothing super extensive, so give it a try and let me know what you think!

**Comment by mew1033** [comment]
@Matir Looks awesome so far! Is this the right place to mention if I notice things? If so, I noticed something! ;-)
The challenges on the scoreboard still show the original amount of points for someone who hasn't solved the challenge yet. I tried to steal the configService thing from the directives.js file and apply it in the challenges.js file, but I couldn't make it work. :-( The last part of the section that shows the challenges now looks like this:
```
        var currentPoints = chall.points;

        currentPoints = Math.floor(chall.points / Math.max(chall.solves, 1));

        if (chall.answered)
          return "Solved! Currently worth " + currentPoints + " points";
        else
          return currentPoints + " points";
```

**Comment by Matir** [comment]
Here works.  Do you mean the "Jeopardy Style" display where the cards flip over to reveal their score?

**Comment by mew1033** [comment]
Yup. The scoring and everything is all working, I just noticed that even after a challenge had had multiple solves and was consequently worth fewer points, the cards would still show the original amount.


Another idea (maybe I should make another issue?): It'd be nice if there was some way to give the first person (or two) who solved the challenge a few extra points. That way, at the end of the competition, if the top two players solved all the same challenges, one would still win. Whoever was faster.

**Comment by Matir** [comment]
Commit c315da8 should have the challenge grid issue fixed.

Giving a "first blood" bonus should be pretty trivial, though some of the UI stuff might need tweaks to reflect it properly.  Opening a new issue would make sense, just so I can track it separately.
