### ISSUE TITLE
Enable countdown timer

### ISSUE THREAD

**Issue by mew1033** [Matir/pwnableweb-scoreboard#74]
I can't seem to make the countdown timer work... Are you just supposed to add the following to the config.py file:
```
game_start = '2016-06-02T09:00:00-0900'
game_end = '2016-06-02T16:00:00-0900'
```

**Comment by Matir** [comment]
Sorry I didn't get back to you sooner, but it would look something like:

GAME_TIME = ('2016-06-02T09:00:00-0900', '2016-06-02T16:00:00-0900')
